import { pgTable, text, integer, decimal } from 'drizzle-orm/pg-core';

export const currencies = pgTable('currencies', {
    code: text('code').primaryKey(), // ISO 4217: USD, EUR, KZT
    name: text('name').notNull(), // US Dollar, Euro, Kazakhstani Tenge
    symbol: text('symbol').notNull(), // $, €, ₸
    decimalPlaces: integer('decimal_places').default(2).notNull(),
    exchangeRate: decimal('exchange_rate', { precision: 20, scale: 10 }).default('1').notNull(), // Rate relative to USD
});

// Pre-defined currencies to seed
export const DEFAULT_CURRENCIES = [
    { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', decimalPlaces: 2 },
    { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', decimalPlaces: 2 },
    { code: 'ALL', name: 'Albanian Lek', symbol: 'L', decimalPlaces: 2 },
    { code: 'AMD', name: 'Armenian Dram', symbol: '֏', decimalPlaces: 2 },
    { code: 'ANG', name: 'Netherlands Antillian Guilder', symbol: 'ƒ', decimalPlaces: 2 },
    { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', decimalPlaces: 2 },
    { code: 'ARS', name: 'Argentine Peso', symbol: '$', decimalPlaces: 2 },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimalPlaces: 2 },
    { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', decimalPlaces: 2 },
    { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', decimalPlaces: 2 },
    { code: 'BAM', name: 'Bosnia and Herzegovina Convertible Mark', symbol: 'KM', decimalPlaces: 2 },
    { code: 'BBD', name: 'Barbados Dollar', symbol: 'Bds$', decimalPlaces: 2 },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimalPlaces: 2 },
    { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', decimalPlaces: 2 },
    { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', decimalPlaces: 3 },
    { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', decimalPlaces: 0 },
    { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', decimalPlaces: 2 },
    { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', decimalPlaces: 2 },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimalPlaces: 2 },
    { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$', decimalPlaces: 2 },
    { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', decimalPlaces: 2 },
    { code: 'BWP', name: 'Botswana Pula', symbol: 'P', decimalPlaces: 2 },
    { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', decimalPlaces: 2 },
    { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', decimalPlaces: 2 },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', decimalPlaces: 2 },
    { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', decimalPlaces: 2 },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', decimalPlaces: 2 },
    { code: 'CLF', name: 'Chilean Unidad de Fomento', symbol: 'CLF', decimalPlaces: 4 },
    { code: 'CLP', name: 'Chilean Peso', symbol: '$', decimalPlaces: 0 },
    { code: 'CNH', name: 'Offshore Chinese Renminbi', symbol: '¥', decimalPlaces: 2 },
    { code: 'CNY', name: 'Chinese Renminbi', symbol: '¥', decimalPlaces: 2 },
    { code: 'COP', name: 'Colombian Peso', symbol: '$', decimalPlaces: 2 },
    { code: 'CRC', name: 'Costa Rican Colon', symbol: '₡', decimalPlaces: 2 },
    { code: 'CUP', name: 'Cuban Peso', symbol: '$MN', decimalPlaces: 2 },
    { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc', decimalPlaces: 2 },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', decimalPlaces: 2 },
    { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', decimalPlaces: 0 },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimalPlaces: 2 },
    { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', decimalPlaces: 2 },
    { code: 'DZD', name: 'Algerian Dinar', symbol: 'DA', decimalPlaces: 2 },
    { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', decimalPlaces: 2 },
    { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', decimalPlaces: 2 },
    { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', decimalPlaces: 2 },
    { code: 'EUR', name: 'Euro', symbol: '€', decimalPlaces: 2 },
    { code: 'FJD', name: 'Fiji Dollar', symbol: 'FJ$', decimalPlaces: 2 },
    { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'FOK', name: 'Faroese Króna', symbol: 'kr', decimalPlaces: 2 },
    { code: 'GBP', name: 'Pound Sterling', symbol: '£', decimalPlaces: 2 },
    { code: 'GEL', name: 'Georgian Lari', symbol: '₾', decimalPlaces: 2 },
    { code: 'GGP', name: 'Guernsey Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', decimalPlaces: 2 },
    { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', decimalPlaces: 2 },
    { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', decimalPlaces: 0 },
    { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', decimalPlaces: 2 },
    { code: 'GYD', name: 'Guyanese Dollar', symbol: 'G$', decimalPlaces: 2 },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', decimalPlaces: 2 },
    { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', decimalPlaces: 2 },
    { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', decimalPlaces: 2 },
    { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', decimalPlaces: 2 },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', decimalPlaces: 2 },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimalPlaces: 2 },
    { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', decimalPlaces: 2 },
    { code: 'IMP', name: 'Manx Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimalPlaces: 2 },
    { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', decimalPlaces: 3 },
    { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', decimalPlaces: 2 },
    { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', decimalPlaces: 0 },
    { code: 'JEP', name: 'Jersey Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', decimalPlaces: 2 },
    { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', decimalPlaces: 3 },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimalPlaces: 0 },
    { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', decimalPlaces: 2 },
    { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', decimalPlaces: 2 },
    { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', decimalPlaces: 2 },
    { code: 'KID', name: 'Kiribati Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', decimalPlaces: 0 },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimalPlaces: 0 },
    { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', decimalPlaces: 3 },
    { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', decimalPlaces: 2 },
    { code: 'LAK', name: 'Lao Kip', symbol: '₭', decimalPlaces: 2 },
    { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', decimalPlaces: 2 },
    { code: 'LKR', name: 'Sri Lanka Rupee', symbol: 'Rs', decimalPlaces: 2 },
    { code: 'LRD', name: 'Liberian Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', decimalPlaces: 2 },
    { code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', decimalPlaces: 3 },
    { code: 'MAD', name: 'Moroccan Dirham', symbol: 'DH', decimalPlaces: 2 },
    { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', decimalPlaces: 2 },
    { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', decimalPlaces: 2 },
    { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', decimalPlaces: 2 },
    { code: 'MMK', name: 'Burmese Kyat', symbol: 'K', decimalPlaces: 2 },
    { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', decimalPlaces: 2 },
    { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', decimalPlaces: 2 },
    { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', decimalPlaces: 2 },
    { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', decimalPlaces: 2 },
    { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', decimalPlaces: 2 },
    { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', decimalPlaces: 2 },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$', decimalPlaces: 2 },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimalPlaces: 2 },
    { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', decimalPlaces: 2 },
    { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', decimalPlaces: 2 },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimalPlaces: 2 },
    { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', decimalPlaces: 2 },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimalPlaces: 2 },
    { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', decimalPlaces: 2 },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', decimalPlaces: 2 },
    { code: 'OMR', name: 'Omani Rial', symbol: '﷼', decimalPlaces: 3 },
    { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', decimalPlaces: 2 },
    { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', decimalPlaces: 2 },
    { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', decimalPlaces: 2 },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimalPlaces: 2 },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', decimalPlaces: 2 },
    { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', decimalPlaces: 2 },
    { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲', decimalPlaces: 0 },
    { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', decimalPlaces: 2 },
    { code: 'RON', name: 'Romanian Leu', symbol: 'lei', decimalPlaces: 2 },
    { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', decimalPlaces: 2 },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽', decimalPlaces: 2 },
    { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', decimalPlaces: 0 },
    { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', decimalPlaces: 2 },
    { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', decimalPlaces: 2 },
    { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', decimalPlaces: 2 },
    { code: 'SDG', name: 'Sudanese Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimalPlaces: 2 },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', decimalPlaces: 2 },
    { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', decimalPlaces: 2 },
    { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', decimalPlaces: 2 },
    { code: 'SOS', name: 'Somali Shilling', symbol: 'S', decimalPlaces: 2 },
    { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', decimalPlaces: 2 },
    { code: 'SYP', name: 'Syrian Pound', symbol: '£', decimalPlaces: 2 },
    { code: 'SZL', name: 'Eswatini Lilangeni', symbol: 'L', decimalPlaces: 2 },
    { code: 'THB', name: 'Thai Baht', symbol: '฿', decimalPlaces: 2 },
    { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', decimalPlaces: 2 },
    { code: 'TMT', name: 'Turkmenistan Manat', symbol: 'T', decimalPlaces: 2 },
    { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', decimalPlaces: 3 },
    { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', decimalPlaces: 2 },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimalPlaces: 2 },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', decimalPlaces: 2 },
    { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', decimalPlaces: 2 },
    { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', decimalPlaces: 2 },
    { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', decimalPlaces: 2 },
    { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', decimalPlaces: 0 },
    { code: 'USD', name: 'United States Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', decimalPlaces: 2 },
    { code: 'UZS', name: 'Uzbekistani So\'m', symbol: 'so\'m', decimalPlaces: 2 },
    { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S', decimalPlaces: 2 },
    { code: 'VND', name: 'Vietnamese Đồng', symbol: '₫', decimalPlaces: 0 },
    { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', decimalPlaces: 0 },
    { code: 'WST', name: 'Samoan Tālā', symbol: 'WS$', decimalPlaces: 2 },
    { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', decimalPlaces: 0 },
    { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', decimalPlaces: 2 },
    { code: 'XCG', name: 'Caribbean Guilder', symbol: 'Cg', decimalPlaces: 2 },
    { code: 'XDR', name: 'Special Drawing Rights', symbol: 'SDR', decimalPlaces: 5 },
    { code: 'XOF', name: 'West African CFA franc', symbol: 'CFA', decimalPlaces: 0 },
    { code: 'XPF', name: 'CFP Franc', symbol: '₣', decimalPlaces: 0 },
    { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', decimalPlaces: 2 },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimalPlaces: 2 },
    { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', decimalPlaces: 2 },
    { code: 'ZWG', name: 'Zimbabwean Dollar', symbol: 'Z$', decimalPlaces: 2 },
    { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', decimalPlaces: 2 },
];

export type Currency = typeof currencies.$inferSelect;
export type NewCurrency = typeof currencies.$inferInsert;
